Fix fallback code and increase compatibility with older browsers
badaix/snapweb pull request #13
Opened 2020-10-03 14:30 UTC by Zopieux

* using `this.ctx.getOutputTimestamp().contextTime || (fallback)` does not have the intended effect of falling back if `getOutputTimestamp` doesn't exist because calling it throws a JS exception (infamous *undefined is not a function*). This fixes the problem by checking the function exists first.
* I'm running Snapweb on a smart TV with an ancient Chrome build (53.0 from 2016) and can only get it to work if `AudioContext` has no constructor options.

2020-10-04 19:26 UTC, badaix requested changes

2020-10-04 19:26 UTC, badaix commented on page/snapstream.ts
> +                        if (navigator.userAgent.match(/Chrome\/53\.0/)) {
According to the [Browser compatibility table](https://developer.mozilla.org/de/docs/Web/API/AudioContext/AudioContext) Chrome has full AudioContext constructor support starting with version 55.
I think we should check for versions < 55 rather than just 53.
The version can be detected [like this](https://stackoverflow.com/questions/4900436/how-to-detect-the-installed-chrome-version):

```js
function getChromeVersion () {     
    var raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
    return raw ? parseInt(raw[2], 10) : false;
}
```

2020-10-04 22:21 UTC, Zopieux commented on page/snapstream.ts
> +                        if (navigator.userAgent.match(/Chrome\/53\.0/)) {
Done, thanks.

2020-10-05 07:24 UTC, merged

2020-10-05 07:24 UTC, badaix commented
Thanks!